<a href="https://colab.research.google.com/github/ANUDHEERPARIMI/PyTorch/blob/PyTorch/Autograd_Neural_Net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

x->w->sigmoid->y_pred->Loss

Normal Calculation

In [2]:
y=torch.tensor(0.0)
x=torch.tensor(6.7)

w=torch.tensor(1.0)
b=torch.tensor(0.0)

In [3]:
def binary_cross_entropy_loss(y_pred, y_true):
    ep=1e-8
    y_pred=torch.clamp(y_pred,ep,1-ep)
    return -torch.mean(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))

In [4]:
z=w*x+b
y_pred=torch.sigmoid(z)
Loss=binary_cross_entropy_loss(y_pred,y)

In [5]:
Loss

tensor(6.7012)

In [6]:
z

tensor(6.7000)

In [7]:
#Derivatives

dloss_dy_pred=(y_pred-y)/(y_pred*(1-y_pred))

dy_pred_dz=y_pred*(1-y_pred)

dz_dw=x
dz_db=1

dloss_dw=dloss_dy_pred*dy_pred_dz*dz_dw
dloss_db=dloss_dy_pred*dy_pred_dz*dz_db

In [8]:
dloss_dw

tensor(6.6918)

In [9]:
dloss_db

tensor(0.9988)

Using AutoGrad

In [10]:
y=torch.tensor(0.0)
x=torch.tensor(6.7)

w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [11]:
z=w*x+b

In [12]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [13]:
y_pred=torch.sigmoid(z)

In [14]:
loss=binary_cross_entropy_loss(y_pred,y)

In [15]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [16]:
loss.backward()

In [17]:
w.grad

tensor(6.6918)

In [18]:
b.grad

tensor(0.9988)

In [19]:
#Vector Level

In [20]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [30]:
y=(x**2).sum()

In [31]:
y.backward()

In [32]:
x.grad


tensor([2., 4., 6.])

In [33]:
x.grad.zero_()

tensor([0., 0., 0.])

In [34]:
x

tensor([1., 2., 3.], requires_grad=True)

Detach gradient

In [35]:
x.requires_grad_(False)

tensor([1., 2., 3.])

In [37]:
y.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [40]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [44]:
z=x.detach()
z

tensor(2.)

In [45]:
z

tensor(2.)

In [47]:
y=x**2

In [48]:
y

tensor(4., grad_fn=<PowBackward0>)

In [49]:
z.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [50]:
y.backward()

In [51]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)