<a href="https://colab.research.google.com/github/ANUDHEERPARIMI/PyTorch/blob/PyTorch/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.empty(2,3)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.3086e-39, 4.2428e-38, 1.5614e-39]])

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.4067, 0.1696, 0.5400],
        [0.6765, 0.2997, 0.4190]])

In [ ]:
#To generate same random values

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(0,10,10,dtype=torch.float32)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [ ]:
torch.full((5,5),10)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

In [ ]:
x=torch.tensor([[1,2,3],[2,3,4]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[              0,       372318880,       354294400],
        [133381778088784,               1,              25]])

In [ ]:
temp=x.shape
torch.empty_like(x)

tensor([[              0,       372319008,       354294400],
        [133377833466160,               0,               0]])

In [ ]:
x=torch.ones(2,3)

In [ ]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x.to(dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [ ]:
x*2

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [ ]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
y=torch.full((2,3),5)

In [ ]:
y

tensor([[5, 5, 5],
        [5, 5, 5]])

In [ ]:
x/y

tensor([[0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000]])

In [ ]:
z=torch.full((2,2),5)

In [ ]:
x=torch.tensor([[1,1.5,2],[1,1.5,9]])

In [ ]:
torch.var(x)

tensor(9.7667)

In [ ]:
torch.min(x)

tensor(1.)

In [ ]:
torch.max(x)

tensor(9.)

In [ ]:
torch.std(x)

tensor(3.1252)

In [ ]:
torch.matmul(x,torch.transpose(x,0,1))

tensor([[ 7.2500, 21.2500],
        [21.2500, 84.2500]])

In [ ]:
y=torch.tensor([[[1,2,3],[2,3,4],[4,5,6]],[[1,2,3],[2,3,4],[4,5,6]]])

In [ ]:
y.transpose(1,2)

tensor([[[1, 2, 4],
         [2, 3, 5],
         [3, 4, 6]],

        [[1, 2, 4],
         [2, 3, 5],
         [3, 4, 6]]])

In [ ]:
x=torch.tensor([[-1,2,-3]])
torch.abs(x)

tensor([[1, 2, 3]])

In [ ]:
x.sum(axis=0)

tensor([-1,  2, -3])

In [ ]:
x.flatten()

tensor([-1,  2, -3])

In [ ]:
x=torch.tensor([1,2,3],requires_grad=True,dtype=torch.float32)

In [ ]:
y=x**2*torch.cos(x)

In [ ]:
loss=y.mean()

In [ ]:
loss.backward()

In [ ]:
x.grad

tensor([ 0.0797, -1.7673, -2.4033])

In [ ]:
#Neural Net
x=torch.tensor([[1,2],[2,3]])

w=torch.tensor([[1,2],[2,4]],requires_grad=True,dtype=torch.float32)

b=torch.tensor([[1,2]],requires_grad=True,dtype=torch.float32)

In [ ]:
x*w

tensor([[ 1.,  4.],
        [ 4., 12.]], grad_fn=<MulBackward0>)

In [ ]:
x*w+b

tensor([[ 2.,  6.],
        [ 5., 14.]], grad_fn=<AddBackward0>)

In [ ]:
torch.full((2,2),1)

tensor([[1, 1],
        [1, 1]])

In [ ]:
import torch

x = torch.empty((2, 3, 1))
y = torch.unsqueeze(x, 1)
print(x.shape)  # torch.Size([2, 3, 1])
print(y.shape)


torch.Size([2, 3, 1])
torch.Size([2, 1, 3, 1])


In [ ]:
x=torch.tensor(3.0,requires_grad=True)
y=torch.tensor(4.0,requires_grad=True)

In [ ]:
x=torch.tensor([3,4,5],requires_grad=True,dtype=torch.float32)


In [ ]:
y=x**2
z=torch.cos(x)

In [ ]:
a=y+z

In [ ]:
temp=a.mean()

In [ ]:
temp.backward()

In [ ]:
x.grad*x.size(0)

tensor([ 5.8589,  8.7568, 10.9589])

In [ ]:
x.size()

torch.Size([3])

In [ ]:
torch.ones_like(a)

tensor([1., 1., 1.])